#!/usr/bin/python3
"""
Unittest for BaseModel class
"""
import unittest
from models.base_model import BaseModel


class TestBaseModel(unittest.TestCase):
    """Class to test BaseModel"""
    def test_str(self):
        """test __str__ method"""
        model1 = BaseModel()
		p
